- .github/workflows/assign-new-issues.yml
Setup workflow which assigns new repo issues to organization project
> tech(workflow): Assign new issues to project

- .github/workflows/checks.yml
- .github/workflows/storybook.yml
- README.md
tech: добавление проверок для PR
tech: добавление публикации storybook в GitHub Pages
> tech: проверки и storybook

- packages/core/tsconfig.json
- packages/icons/tsconfig.json
- tsconfig.json
- Для общего tsconfig выставлен параметр `noEmit`
- Свойства emit вынесены в конфигурации пакетов
> tech: tsconfig настроен на локальную разработку

- packages/core/src/TextField/BaseTextField.tsx
- packages/core/src/TextField/TextField.tsx
- packages/core/src/TextField/elements/Bottom.tsx
- packages/core/src/TextField/stories/TextField.story.tsx
- packages/core/src/TextField/styles/index.ts
- packages/core/src/TextField/styles/types.ts
Исправлено: отслеживание количества строк в режиме `multiline`, получение количества символов из `defaultValue`, скрытие `placeholder` для `firefox`.
Доработано: добавлен переход для появления элемента `bottom`, добавлен пропс `bottomIsAbsolute` для включения абсолютного позиционирования `bottom`
> fix(TextField): Внесены исправления и доработки

- .storybook/custom-components/SourceTabs.tsx
- package.json
- packages/core/styles/engine/makeStyles/makeStyles.ts
- packages/icons/storybook/Icons.story.tsx
- packages/icons/storybook/groups.ts
- scripts/figma/src/api/config.ts
- scripts/figma/src/icons/index.ts
- scripts/figma/src/icons/utils/getIconImportTemplate.ts
- scripts/figma/src/icons/utils/getIconJsxFullName.ts
- yarn.lock
> docs: Добавлен storybook по иконкам

- packages/core/styles/engine/theme/createTheme/types.ts
- scripts/cli/src/components.ts
> fix(new_script): Исправлен баг с SingleLine импортом Props в ComponentsProps

- packages/core/src/index.ts
- packages/core/src/unstyled/If/If.tsx
- packages/core/src/unstyled/If/__tests__/If.test.tsx
- packages/core/src/unstyled/If/index.ts
- packages/core/src/unstyled/If/stories/If.story.tsx
- packages/core/src/unstyled/If/types.ts
- packages/core/src/unstyled/Switch/Case/Case.tsx
- packages/core/src/unstyled/Switch/Case/index.ts
- packages/core/src/unstyled/Switch/Case/types.ts
- packages/core/src/unstyled/Switch/Switch.tsx
- packages/core/src/unstyled/Switch/__tests__/Switch.test.tsx
- packages/core/src/unstyled/Switch/index.ts
- packages/core/src/unstyled/Switch/stories/Switch.story.tsx
- packages/core/src/unstyled/Switch/types.ts
Если кто-то кодил на Vue - видел, что там пишутся template вместо jsx(как правило). Есть там интересные подходы касаемо If. Попробовал к нам в React добавить нечто подобное, чтобы ?:, &&, || перестали быть в нашем react-jsx коде. Мне кажется так повышается читаемость и в целом код становится получше.  Что думаете на счет того, чтобы добавить эти компоненты к нам в дизайн-систему как unstyled components?
> feat: Добавлены компоненты If, Switch

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/icons/CHANGELOG.md
- packages/icons/package.json
- @quarx-ui/core@1.4.0
- @quarx-ui/icons@1.0.5
> chore(release): publish

- scripts/cli/src/componentLayouts/root.ts
> feat: Добавить обработку hidden для yarn new

- packages/core/src/main/Selections/Selection/__tests__/__snapshots__/Selection.test.tsx.snap
- packages/core/src/main/Selections/Selection/styles/index.ts
- packages/core/src/main/Selections/SelectionGroup/SelectionGroup.tsx
- packages/core/src/main/Selections/SelectionGroup/__tests__/SelectionGroup.test.tsx
- packages/core/src/main/Selections/SelectionGroup/__tests__/__snapshots__/SelectionGroup.test.tsx.snap
- packages/core/src/main/Selections/SelectionGroup/index.ts
- packages/core/src/main/Selections/SelectionGroup/stories/SelectionGroup.story.tsx
- packages/core/src/main/Selections/SelectionGroup/styles/constants.ts
- packages/core/src/main/Selections/SelectionGroup/styles/index.ts
- packages/core/src/main/Selections/SelectionGroup/styles/types.ts
- packages/core/src/main/Selections/SelectionGroup/types.ts
- packages/core/src/main/Selections/index.ts
- packages/core/styles/engine/theme/createTheme/types.ts
> feat(SelectionGroup): Добавлен компонент SelectionGroup

- packages/core/src/main/Button/BaseButton/styles/index.ts
- packages/core/src/main/Checkbox/styles/index.ts
- packages/core/src/main/Chips/styles/index.ts
- packages/core/src/main/Link/styles/index.ts
- packages/core/src/main/RadioButton/styles/index.ts
- packages/core/src/main/Selections/Selection/styles/index.ts
- packages/core/src/main/Switcher/__tests__/__snapshots__/Switcher.test.tsx.snap
- packages/core/src/main/Switcher/styles/index.ts
- packages/core/src/main/Tabs/TabsContained/TabItemContained/styles/index.ts
- packages/core/src/main/Tabs/TabsSegmented/TabItemSegmented/styles/index.ts
- packages/core/stories/style/colors.story.tsx
- packages/core/styles/engine/theme/palette/getDarkPalette.ts
- packages/core/styles/engine/theme/palette/getLightPalette.ts
- packages/core/styles/engine/theme/palette/types.ts
- packages/icons/storybook/Icons.story.tsx
Их значения теперь зависят от выбранной цветовой темы (light/dark)
> feat(palette)!: Цвета фокуса `dark` и `light` в палитре заменены на `main` и `inverse`

- packages/core/src/system/Stack/Stack.tsx
- packages/core/src/system/Stack/__tests__/Stack.test.tsx
- packages/core/src/system/Stack/__tests__/__snapshots__/Stack.test.tsx.snap
- packages/core/src/system/Stack/index.ts
- packages/core/src/system/Stack/stories/Stack.story.tsx
- packages/core/src/system/Stack/styles/constants.ts
- packages/core/src/system/Stack/styles/index.ts
- packages/core/src/system/Stack/styles/maps.ts
- packages/core/src/system/Stack/styles/types.ts
- packages/core/src/system/Stack/styles/vars.ts
- packages/core/src/system/Stack/types.ts
- packages/core/src/system/index.ts
- packages/core/styles/engine/theme/createTheme/types.ts
- packages/core/utils/addCssToElement.ts
- packages/core/utils/index.ts
Предназначен для позиционирования элементов, расположенных на одной оси с равными отступами
Resolve #163
> feat: Добавлен системный компонент **Stack**

- package.json
- scripts/cli/new/src/creature/structures/core/index.ts
- scripts/cli/new/src/creature/structures/core/layouts/root.ts
- scripts/cli/new/src/creature/structures/core/layouts/storybook.ts
- scripts/cli/new/src/creature/structures/core/layouts/styles.ts
- scripts/cli/new/src/creature/structures/core/layouts/tests.ts
> feature(scripts:new): Изменена структура storybook

- packages/core/src/system/Divider/types.ts
> feat: Добавлен компонент **Divider**

- packages/core/src/main/Tabs/TabsContained/TabsContained.tsx
- packages/core/src/main/Tabs/TabsContained/styles/index.ts
- packages/core/src/main/Tabs/TabsDefault/TabItemDefault/styles/index.ts
- packages/core/src/main/Tabs/TabsDefault/TabsDefault.tsx
- packages/core/src/main/Tabs/TabsSegmented/TabsSegmented.tsx
- packages/core/src/main/Tabs/TabsSegmented/styles/index.ts
- packages/core/src/main/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
- packages/core/src/main/Tabs/stories/Tabs.story.tsx
- packages/core/storybook/DisplayVariants/style.ts
Исправлено:
1. Для итерируемых элементов добавлены `key`;
2. Для табов отключен перенос по словам.
> fix(Tabs): Мелкие исправления

- packages/core/src/main/Chips/__tests__/__snapshots__/Chips.test.tsx.snap
- packages/core/src/main/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
- packages/core/src/main/SidePage/__tests__/__snapshots__/SidePage.test.tsx.snap
- packages/core/src/system/Popup/__tests__/__snapshots__/Popup.test.tsx.snap
- packages/core/src/system/Transition/Transition.tsx
- packages/core/src/system/Transition/types.ts
- scripts/cli/new/index.ts
> Компонент **Transition** переключен на использование `css` вместо `style`

- README.md
- packages/core/README.md
> fix: Introduction story. Установка

- packages/core/src/main/Accordion/Accordion.tsx
- packages/core/src/main/Accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
- packages/core/src/main/Accordion/styles/index.ts
- packages/core/styles/engine/theme/palette/createPalette.ts
- packages/core/styles/engine/theme/palette/getDarkPalette.ts
- packages/core/styles/engine/theme/palette/getLightPalette.ts
- packages/core/styles/engine/theme/palette/mergeObjectProps.ts
> fix(palette): Исправлено переопределение цветов при создании темы

- .gitignore
- packages/core/stories/style/typography.story.tsx
- packages/core/styles/engine/theme/createTheme/createTheme.ts
- packages/core/styles/engine/theme/createTheme/types.ts
- packages/core/styles/engine/theme/index.ts
- packages/core/styles/engine/theme/typography/baseTypography/baseTypography.ts
- packages/core/styles/engine/theme/typography/baseTypography/constants.ts
- packages/core/styles/engine/theme/typography/baseTypography/index.ts
- packages/core/styles/engine/theme/typography/baseTypography/types.ts
- packages/core/styles/engine/theme/typography/constants.ts
- packages/core/styles/engine/theme/typography/helpers/createGetTypographyVariant.ts
- packages/core/styles/engine/theme/typography/helpers/createPxToRem.ts
- packages/core/styles/engine/theme/typography/helpers/index.ts
- packages/core/styles/engine/theme/typography/index.ts
- packages/core/styles/engine/theme/typography/map.ts
- packages/core/styles/engine/theme/typography/types.ts
- packages/core/styles/engine/theme/typography/typography.ts
- packages/core/styles/engine/utils/deepMerge/deepMerge.js
- packages/core/styles/typography/typography.ts
- Добавлена базовая типографика **baseTypography** и функция для её создания
- В **theme** добавлено поле **typography.base**
- Обновлена документация по типографике
> feat(theme): В тему добавлена базовая типографика

- packages/core/src/main/Dropdown/Dropdown.tsx
- packages/core/src/main/Dropdown/DropdownItem/DropdownItem.tsx
- packages/core/src/main/Dropdown/DropdownItem/types.ts
- packages/core/src/main/Dropdown/DropdownItemsGroup/__tests__/__snapshots__/DropdownItemsGroup.test.tsx.snap
- packages/core/src/main/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
- packages/core/src/main/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
- packages/core/src/main/Modal/storybook/footerDirection/description.md
- packages/core/src/main/Modal/storybook/footerDirection/index.tsx
- packages/core/src/main/SidePage/__tests__/__snapshots__/SidePage.test.tsx.snap
- packages/core/src/system/FooterBlock/FooterBlock.tsx
- packages/core/src/system/FooterBlock/constants.ts
- packages/core/src/system/FooterBlock/styles/index.ts
- packages/core/src/system/HeaderBlock/HeaderBlock.tsx
Для FooterBlock добавлены свойства `vertical-reverse` и `horizontal-reverse` для направления кнопок в обратном порядке.
Исправлен в `Dropdown` пустой header.
Исправлено в `DropdownItem`:
1. Пустой description;
2. Исключение пропсов используемых в стилях.
> fix: Мелкие исправления

- .eslintrc.js
- packages/core/src/experimental/DatePicker/components/Block/components/FooterDatePicker/FooterDatePicker.tsx
- packages/core/src/experimental/DatePicker/components/DateField/utils/format.ts
- packages/core/src/experimental/DatePicker/components/DateField/utils/placeholder.ts
- packages/core/src/system/DelayedMounter/useDelayedMounter.ts
- packages/core/src/system/OverScreen/OverScreen.tsx
- packages/core/utils/object/omitProps/index.ts
Добавлена проверка зависимостей для useEnhancedEffect. Исправлены ошибки линта
> fix(DelayedMounter): Фикс использования устаревшего значения
